apiVersion: apps/v1
kind: CronJob
metadata:
  name: crawler-cronjob
spec:
  schedule: "0 */8 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: crawlercontainer
              image: crawwlerapp:latest
              envFrom:
                - configMapRef:
                    name: crawler-app-config
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 1
---
apiVersion: apps/v1
kind: ConfigMap
metadata:
  name: crawler-app-config
data:
  DB_URL: "192.168.2.9:27017"
